"""Update actor age to actor bday

Revision ID: ab5f0882acd2
Revises: 
Create Date: 2020-06-28 18:23:29.991788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab5f0882acd2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actor', sa.Column('bday', sa.DateTime(), nullable=False))
    op.alter_column('actor', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('actor', 'age')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actor', sa.Column('age', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('actor', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('actor', 'bday')
    # ### end Alembic commands ###
